# -*- coding: utf-8 -*-
"""my_libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKT64aVQ2fNVJZ1OJz4e4loF3vJE2e7W
"""

!pip install transformers==3.0.2

!pip install streamlit

import streamlit as st
import joblib
import re
from collections import defaultdict
from transformers import RobertaTokenizer
import numpy as np
import tensorflow as tf
from tensorflow import keras

from google.colab import drive
drive.mount('/content/drive')

tokenizer = RobertaTokenizer.from_pretrained('roberta-base', truncation=True, do_lower_case=True)

