# -*- coding: utf-8 -*-
"""Questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yUSaoVgKTgQ-p-H_DaiTzakvF1uTcDC
"""

import sqlite3

conn = sqlite3.connect('sentiment_responses.db')
c = conn.cursor()

c.execute('''CREATE TABLE IF NOT EXISTS responses
          (name TEXT, question TEXT, response TEXT)''')

c.execute("select * from responses")

questions = [
    ("Are you feeling upset or sad?", 5),
    ("Is there something bothering you?", 4),
    ("Do you need someone to talk to?", 3),
    ("Would you like to share what's on your mind?", 2),
]

def ask_questions_and_store_responses(name):
    for question, _ in questions:
        response = input(question + " (Yes/No): ")
        c.execute("INSERT INTO responses (name, question, response) VALUES (?, ?, ?)", (name, question, response))
    conn.commit()

name = input("Please enter your name: ")
ask_questions_and_store_responses(name)

def view_responses():
    # Query the database to view the inserted data
    c.execute("SELECT * FROM responses")
    rows = c.fetchall()
    print("\nData in the database:")
    for row in rows:
        print(row)

view_responses()

import sqlite3
import csv

# Connect to the SQLite database
conn = sqlite3.connect('sentiment_responses.db')
c = conn.cursor()

# Query the database to fetch all records
c.execute("SELECT * FROM responses")
rows = c.fetchall()

# Write the data to a CSV file
with open('sentiment_responses.csv', 'w', newline='', encoding='utf-8') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['Name', 'Question', 'Response'])
    csvwriter.writerows(rows)

print("Data exported to sentiment_responses.csv")

# Close the database connection
conn.close()

